name: prometheus-pkg-exporter
version: '1.0.0'
grade: stable
summary: Export textfile-based apt-repositories metrics from parsed log data
description: >
    This snap provides a prometheus exporter for apt repositories using https://github.com/margau/pkg-exporter.
confinement: strict
license: GPL-3.0
base: core20
architectures:
  - build-on: amd64

plugs:
  apt-exporter-files:
    interface: system-files
    read:
      - /usr/share/dpkg/cputable
      - /usr/share/dpkg/tupletable
      - /var/lib/snapd/hostfs/var/lib/apt/lists
      - /var/lib/snapd/hostfs/var/lib/dpkg/status
      - /var/lib/snapd/hostfs/var/lib/apt/extended_states
      - /var/lib/snapd/hostfs/var/cache/apt/srcpkgcache.bin
      - /var/lib/snapd/hostfs/etc/apt/apt.conf.d
      - /var/lib/snapd/hostfs/etc/apt/sources.list
      - /var/lib/snapd/hostfs/etc/apt/sources.list.d
      - /var/lib/snapd/hostfs/etc/apt/preferences.d

apps:
  apt-exporter:
    command: 'bin/pkg-exporter --rootdir /var/lib/snapd/hostfs/ -d'
    daemon: simple
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - apt-exporter-files
      - network-bind

parts:
  pkg-exporter:
    plugin: python
    #TODO: Point to the upstream repo after the PR(https://github.com/margau/pkg-exporter/pull/20) is merged.
    source: https://github.com/sudeephb/pkg-exporter.git
    stage-packages:
      - python3-apt
