name: prometheus-apt-exporter
version: '1.0.0'
grade: stable
summary: Export textfile-based apt-repositories metrics from parsed log data
description: >
    This snap provides a prometheus exporter for apt repositories using https://github.com/margau/pkg-exporter.
confinement: strict
license: GPL-3.0
base: core20
architectures:
  - build-on: amd64

layout:
  /usr/share/dpkg/cputable:
    bind-file: $SNAP_DATA/usr/share/dpkg/cputable
  /usr/share/dpkg/tupletable:
    bind-file: $SNAP_DATA/usr/share/dpkg/tupletable
  /etc/apt:
    bind: $SNAP_DATA/etc/apt

plugs:
  host-apt-contents:
    interface: system-files
    read:
      - /var/lib/snapd/hostfs/var/lib/apt/lists
      - /var/lib/snapd/hostfs/var/lib/dpkg/status
      - /var/lib/snapd/hostfs/var/lib/apt/extended_states
      - /var/lib/snapd/hostfs/var/cache/apt/srcpkgcache.bin
      - /var/lib/snapd/hostfs/etc/apt

apps:
  apt-exporter:
    command: 'bin/set_apt_cache_env.sh'
    daemon: simple
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - host-apt-contents
      - network-bind

parts:
  pkg-exporter:
    plugin: python
    source: https://github.com/sudeephb/pkg-exporter.git
    stage-packages:
      - python3-apt
      - dpkg
  set-apt-cache-config:
    plugin: dump
    source: bin
    organize:
      set_apt_cache_env.sh: bin/set_apt_cache_env.sh
